version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: callcenter
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: callcenterdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
