CREATE TABLE IF NOT EXISTS calls (
    id SERIAL PRIMARY KEY,
    caller VARCHAR(100) NOT NULL,
    agent_id INTEGER REFERENCES agents(id),
    status VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT NOW()
);